version: "3.8"
services:
  web:
    build: ./app
    command: python wsgi.py runserver 0.0.0.0:5000
    environment:
      - DB_NAME=my_shop
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
  pg:
    container_name: pg_container2
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_shop
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/my_shop.sql:/docker-entrypoint-initdb.d/1-my_shop.sql
  pgadmin:
    container_name: pgadmin_container2
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
